version: '3.8'

services:

  postgres:
    image: postgres:15.3
    ports:
      - 5432:5432
    env_file:
      - .env

  webapp:
     image: simplenotification:1
     ports:
       - 8000:8000
     command: sh -c "sleep 10 && poetry run alembic upgrade head && poetry run python simple_notification/main.py"
     depends_on:
       - postgres
     env_file:
       - .env