version: '3.8'

services:

  postgres:
    image: postgres:15.3
    ports:
      - 5432:5432
    env_file:
      - .env

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

  # api:
  #   image: simple_notification:latest
  #   ports:
  #     - 8000:8000
  #   command: sh -c "sleep 10 && poetry run alembic upgrade head && poetry run python3 simple_notification/api.py"
  #   depends_on:
  #     - postgres
  #     - redis

  # publish_notifications:
  #   image: simple_notification:latest
  #   command: sh -c "sleep 15 && poetry run python3 simple_notification/publish_notifications.py"
  #   depends_on:
  #     - postgres
  #     - redis
  #     - api
